Add monitor mode
castai/k8s-agent pull request #119
Opened 2023-05-23 19:21 UTC by viktorasm

2023-05-24 18:58 UTC, viktorasm commented on Makefile
> +	docker buildx build --push --platform=linux/amd64,linux/arm64 -t  $(TAG) .
boyscout: fixing this make target after changes were done for multi-arch build.

2023-05-24 18:59 UTC, viktorasm commented on Makefile
> -push:
deleting some unused make targets. for local development, "build" now both builds and pushes multi-arch image.

2023-05-24 19:02 UTC, viktorasm commented on main.go
> +		go func() {
temporary hack to test OOM behavior (to be deleted before merging the PR)

2023-05-24 19:05 UTC, viktorasm commented on internal/services/monitor/monitor.go
> +			m.log.Errorf("k8s events detected: TYPE:%s REASON:%s TIMESTAMP:%s MESSAGE:%s", e.Type, e.Reason, e.LastTimestamp.UTC().Format(time.RFC3339), e.Message)
TODO: exclude `type:normal` events

2023-05-25 08:39 UTC, saumas commented on internal/services/monitor/metadata.go
> +}
This struct is marhaled to json, it should have `json` tags.

2023-05-25 09:05 UTC, saumas requested changes
Looks good. Small comments.

2023-05-25 13:26 UTC, saumas approved these changes

2023-05-29 11:16 UTC, merged